// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeApp() App {
	message := NewMessage()
	greeter := NewGreeter(message)
	event := NewEvent(greeter)
	ruder := NewRuder()
	app := NewApp(event, ruder)
	return app
}

// wire.go:

var EventSet = wire.NewSet(NewEvent, NewMessage, NewGreeter)

var AppSet = wire.NewSet(NewRuder)
