// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeApp() App {
	message := NewMessage()
	greeter := NewGreeter(message)
	event := NewEvent(greeter)
	coreAppService := NewCoreAppService()
	app := NewApp(event, coreAppService)
	return app
}

// wire.go:

var EventProvider = wire.NewSet(NewEvent, NewMessage, NewGreeter)

var ServiceProvider = wire.NewSet(NewCoreAppService, wire.Bind(new(AppService), new(*CoreAppService)))
